#!/bin/bash

source "./lib/utilities.sh"

log_info "Check environment."
if [[ -z "$XDG_CONFIG_HOME" ]]; then
    log_fail "Please set XDG_CONFIG_HOME environment."
    exit 1
fi

log_pass "Start installation."

if [[ ! -d "$XDG_CONFIG_HOME" ]]; then
    log_info "Creates .config directory."
    mkdir -p "$XDG_CONFIG_HOME"
fi

if [[ ! -e "$HOME/.tmux.conf" ]]; then
    ln -s "$(pwd)/.tmux.conf" "$HOME/.tmux.conf"
fi

log_info "Check tmux plugin manager."
if [[ ! -d "$HOME/.tmux/plugins" ]]; then
    log_info "Install tmux plugin manager..."
    # @see https://github.com/tmux-plugins/tpm#installation
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

log_pass "Finish installation."
