#!/bin/bash

source "./lib/utilities.sh"

log_info "Update apt packages"
sudo apt-add-repository ppa:fish-shell/release-3
sudo apt-get update
sudo apt-get install -y fish curl git


log_info "Check environment."
if [[ -z "$XDG_CONFIG_HOME" ]]; then
    log_fail "Please set XDG_CONFIG_HOME environment."
    exit 1
fi

log_pass "Start installation."

if [[ ! -d "$XDG_CONFIG_HOME" ]]; then
    log_info "Creates $XDG_CONFIG_HOME directory."
    mkdir -p "$XDG_CONFIG_HOME"
fi

if [[ ! -e "$HOME/.tmux.conf" ]]; then
    ln -s "$(pwd)/.tmux.conf" "$HOME/.tmux.conf"
fi

log_info "Check tmux plugin manager."
if [[ ! -d "$HOME/.tmux/plugins" ]]; then
    log_info "Install tmux plugin manager..."
    # @see https://github.com/tmux-plugins/tpm#installation
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

log_info "Check git configuration."
if [[ ! -d "${XDG_CONFIG_HOME}git" ]]; then
    log_info "Creates ${XDG_CONFIG_HOME}git directory."
    mkdir -p "${XDG_CONFIG_HOME}git"
    ln -s "$(pwd)/.gitconfig" "${XDG_CONFIG_HOME}git/config"
    ln -s "$(pwd)/.gitignore" "${XDG_CONFIG_HOME}git/ignore"
    ln -s "$(pwd)/.commit_template" "${XDG_CONFIG_HOME}git/.commit_template"
fi

if [[ ! -d "${XDG_CONFIG_HOME}fish" ]]; then
    log_info "Creates ${XDG_CONFIG_HOME}fish directory."
    mkdir -p "${XDG_CONFIG_HOME}fish"
    ln -s "$(pwd)/fish/config.fish" "${XDG_CONFIG_HOME}fish/config.fish"
    ln -s "$(pwd)/fish/fish_plugins" "${XDG_CONFIG_HOME}fish/fish_plugins"
fi

log_pass "Finish installation."
