[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  " auto insert `import` into file when saving.
  let g:go_fmt_command = "goimports"
  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
depends = 'deoplete.nvim'
hook_add = '''
  let g:deoplete#sources#go#gocode_binary = expand($GOPATH . '/bin/gocode')
'''
